version: '3.9'  # Updated to a more recent version

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}  # Set your SA password here
    ports:
      - "1433:1433"
    networks:
      - my-network

  application:
    image: application
    build:
      context: .
      dockerfile: Application/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NoMoreWasteStore;User Id=sa;Password=${SA_PASSWORD}
      - ConnectionStrings__IdentityConnection=Server=sqlserver;Database=NoMoreWasteIdentityStore;User Id=sa;Password=${SA_PASSWORD}
    depends_on:
      - sqlserver
    networks:
      - my-network

  domain:
    image: domain
    build:
      context: .
      dockerfile: Domain/Domain/Dockerfile

  ui:
    image: ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
    networks:
      - my-network

  ef:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    build:
      context: .
      dockerfile: UI/Dockerfile
    command: ["dotnet", "ef", "database", "update", "--context", "IdentityDbContext"]
    environment:
      - ConnectionStrings__IdentityConnection=Server=sqlserver;Database=NoMoreWasteIdentityStore;User Id=sa;Password=${SA_PASSWORD}
    depends_on:
      - sqlserver
    networks:
      - my-network

  domainservices:
    image: domainservices
    build:
      context: .
      dockerfile: Domain/DomainServices/Dockerfile

  infrastructure:
    image: infrastructure
    build:
      context: .
      dockerfile: Infrastructure/Dockerfile

  voedselapi:
    image: voedselapi
    build:
      context: .
      dockerfile: VoedselApi/Dockerfile

networks:
  my-network:
    driver: bridge
